image: "registry.d7z.net/public/archlinux:base-devel"

build:
  before_script:
    - pacman -Syy
    - chown -Rv builder "$(pwd)"
    - mkdir public
  script:
    - su - builder -c "cd $(pwd);makepkg -sf --noconfirm"
    - cp *.zst public
  artifacts:
    paths:
      - public
